version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 5
  complex-logic:
    enabled: false
  method-complexity:
    enabled: false
  method-lines:
    enabled: false
  similar-code:
    enabled: false
plugins:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  fixme:
    enabled: true
exclude_patterns:
  - "coverage/"
  - "docs/"
  - "scripts/"
  - "test/"
  - "*.js"
  - "*.json"
  - "*.md"
  - ".*"
