plugins: [es, html]

extends: [
  plugin:es/no-2018,
  plugin:es/no-2017,
  plugin:es/no-2016,
  plugin:es/no-2015
]

globals:
  Chart: true
  Samples: true

parserOptions:
  sourceType: script
  ecmaFeatures:
    globalReturn: false

rules:
  no-unused-vars: 0
